apiVersion: v1
kind: Pod
metadata:
  labels:
    run: girus
    service: werbserver
  name: girus
spec:
  containers:
  - image: ubuntu
    name: ubuntu 
    args:
      - sleep
      - "1800"
    resources:
      limits: 
        cpu: "0.5"
        memory: "128M"
      requests:
        cpu: "0.3"
        memory: "64M"
  dnsPolicy: ClusterFirst
  restartPolicy: Always
