apiVersion: v1
kind: Pod
metadata:
  labels:
    run: nginx
    service: werbserver
  name: nginx
spec:
  containers:
  - image: nginx
    name: webserver
    volumeMounts:
      - mountPath: /cache
        name: cache-volume
  dnsPolicy: ClusterFirst
  restartPolicy: Always
  volumes:
    - name: cache-volume
      emptyDir:
        sizeLimit: 500M
