apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-secrets
spec:
  selector:
    matchLabels:
      run: nginx
  replicas: 1
  template:
    metadata:
      labels:
        run: nginx
    spec:
      containers:
        - image: nginx
          imagePullPolicy: IfNotPresent
          name: nginx
          resources:
            requests:
              cpu: 0.1
              memory: 256Mi
            limits:
              cpu: 2
              memory: 512Mi
          ports:
            - containerPort: 80
              protocol: TCP
          env:
            - name: USERNAME
              valueFrom:
                secretKeyRef:
                  name: my-secret
                  key: username
            - name: PASSWORD
              valueFrom:
                secretKeyRef:
                  name: my-secret
                  key: password



