apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-docker-secrets
spec:
  selector:
    matchLabels:
      run: hello-docker-secrets
  replicas: 1
  template:
    metadata:
      labels:
        run: hello-docker-secrets
    spec:
      containers:
        - image: rcjeferson/test-private-image:latest
          imagePullPolicy: Always
          name: hello-docker-secrets
          resources:
            requests:
              cpu: 0.1
              memory: 256Mi
            limits:
              cpu: 2
              memory: 512Mi
          ports:
            - containerPort: 8080
              protocol: TCP
      imagePullSecrets:
        - name: docker-hub-secret


